import Head from 'next/head'
import Button from '@/components/Button';
import { useCallback } from "react";
import Particles from "react-particles";
import { loadFull } from "tsparticles";

export default function Home() {
  const particlesInit = useCallback(async engine => {
    console.log(engine);
    // you can initiate the tsParticles instance (engine) here, adding custom shapes or presets
    // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
    // starting from v2 you can add only the features you need reducing the bundle size
    await loadFull(engine);
  }, []);

  const particlesLoaded = useCallback(async container => {
    await console.log(container);
  }, []);

  return (
    <>
      <Head>
        <title>CHS SNHS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* header */}
        <div className='w-full h-screen absolute -z-10 brightness-50'>
          <Particles
            id="tsparticles"
            init={particlesInit}
            loaded={particlesLoaded}
            options={{
              background: {
                color: {
                  // value: "#0f766e",
                  value: "#1e293b"
                },
              },
              fpsLimit: 120,
              interactivity: {
                events: {
                  resize: true,
                },
                modes: {
                  push: {
                    quantity: 4,
                  },
                  repulse: {
                    distance: 200,
                    duration: 0.4,
                  },
                },
              },
              particles: {
                color: {
                  value: "#ffffff",
                },
                links: {
                  color: "#ffffff",
                  distance: 150,
                  enable: true,
                  opacity: 1,
                  width: 1.5,
                },
                collisions: {
                  enable: false,
                },
                move: {
                  direction: "none",
                  enable: true,
                  random: false,
                  speed: 3,
                  straight: false,
                },
                number: {
                  density: {
                    enable: true,
                    area: 1000,
                  },
                  value: 50,
                },
                opacity: {
                  value: 1,
                },
                shape: {
                  type: "circle",
                },
                size: {
                  value: { min: 1, max: 5 },
                },
              },
              detectRetina: true,
            }}
          />
        </div>
        <div className='w-full h-screen flex justify-center items-center flex-col gap-8'>
          <h1 className='text-white lg:text-9xl md:text-7xl text-5xl tracking-wider' style={
            {textShadow: "0 0 14px #06b6d4, 0 0 16px #06b6d4, 0 0 18px #06b6d4"}
          }>Clements SNHS</h1>
          <Button>
            Events
          </Button>
        </div>

        {/* about */}
        <div className='bg-teal-600 w-full flex justify-center items-center px-10 py-16'>
          <div className='text-white max-w-screen-xl flex flex-col gap-6'>
            <h2 className='font-bold lg:text-5xl text-3xl'>
              What is SNHS?
            </h2>
            <p className='lg:text-xl text-lg'>SNHS represents a community of individuals that strive to be the next generation of leaders in industry, science, and research. We aim to empower others to lead future innovation through academic ventures and community service.</p>
          </div>
        </div>
        <div className='w-full py-20 bg-teal-600 text-white flex justify-center items-center'>
          <div className='max-w-screen-xl grow flex flex-row gap-10'>
            <div className='w-[40%] lg:block hidden bg-gray-50 aspect-square'></div>
            <div className='flex flex-col gap-10 items-center grow'>
              <h2 className='font-bold lg:text-5xl text-3xl'>
                UPDATES
              </h2>
              <ul className='lg:text-xl text-lg lg:text-center text-left'>
                <li>The 2022-2023 Interest Meeting is on September 15th in the Downstairs Lecture Hall @3PM!</li>
              </ul>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
